### ISSUE TITLE
Integration Issues with Queue-it in Spring Cloud Environment

### ISSUE THREAD

**Issue by NeeDKK** [queueit/KnownUser.V3.JAVA#13]
We are currently facing challenges integrating Queue-it into our system that is built on Spring Cloud. The demo code provided appears to be tailored for a Servlet-based environment, using javax.servlet.http.HttpServletRequest and HttpServletResponse.
However, in Spring Cloud, especially when working with Spring Cloud Gateway, the environment is reactive, utilizing classes like ServerHttpRequest and ServerHttpResponse. Attempting to cast these reactive classes to the servlet classes results in a casting error:"org.springframework.http.server.reactive.ReactorServerHttpRequest cannot be cast to javax.servlet.http.HttpServletRequest
"
This has created a roadblock in our integration efforts, as we cannot adapt the provided demo code to our non-servlet-based, reactive architecture.

Could you please provide guidance or examples of how we might integrate Queue-it within a Spring Cloud Gateway environment? Any assistance or best practices to follow in this particular scenario would be greatly appreciated.

Thank you for your attention to this matter. We look forward to your support in resolving this integration challenge.

**Comment by csmichaelkamal** [comment]
Hello [NeeDKK](https://github.com/NeeDKK)

Thank you for reaching out to **Queue-it**.

Regarding the Java Connector compatibility issue with Spring boot 3, we want to inform you that we are working on it right now and will update you with the changes you need to make in order to be able to continue your work.

Please, note that the communication will be done via **Queue-it** support representative person
